import React,{useState,useEffect} from 'react';
import {api} from '../api/client';
export default function AnalyticsTab(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[days,setDays]=useState(30),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const [overview,comparison,sentiment]=await Promise.all([api.getOverview(days),api.getPlatformComparison(days),api.getSentimentTrends(days)]);setData({overview,comparison,sentiment});}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[days]);
 return <div className="space-y-6"><header className="flex flex-wrap justify-between items-center gap-4"><div><h1 className="text-2xl font-semibold">Analytics</h1><p className="text-slate-400 mt-2">Real account metrics. Missing data stays missing.</p></div><label className="text-sm">Reporting window<select className="field mt-2" value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>Last {n} days</option>)}</select></label></header>
 {error&&<div className="error" role="alert">{error}<button className="underline block mt-2" onClick={load}>Retry analytics</button></div>}{loading?<p role="status">Loading analytics…</p>:data&&<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[['Reach',data.overview.total_reach],['Impressions',data.overview.total_impressions],['Engagements',data.overview.total_engagements],['Engagement rate',`${data.overview.overall_engagement_rate}%`]].map(([label,value])=><div key={label} className="panel"><p className="text-sm text-slate-400">{label}</p><p className="text-3xl mt-4 font-semibold">{value?.toLocaleString()??'—'}</p></div>)}</div><section className="panel"><h2 className="text-lg font-semibold mb-5">Platform comparison</h2>{data.comparison.platforms?.length?<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr className="text-slate-400 border-b border-slate-700">{['Platform','Reach','Impressions','Engagements','Rate','Followers'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{data.comparison.platforms.map(row=><tr key={row.platform} className="border-b border-slate-800">{[row.platform,row.reach,row.impressions,row.engagements,`${row.engagement_rate}%`,row.followers].map((value,i)=><td key={i} className="p-3">{value?.toLocaleString()??'—'}</td>)}</tr>)}</tbody></table></div>:<p className="text-slate-400 py-10 text-center">No connected platform metrics in this reporting window.</p>}</section><section className="panel"><h2 className="text-lg font-semibold mb-5">Community sentiment</h2>{(data.sentiment.positive_comments_count+data.sentiment.neutral_comments_count+data.sentiment.negative_comments_count)>0?<div className="flex flex-wrap gap-8">{['positive','neutral','negative'].map(label=><p key={label} className="capitalize">{label}: <strong>{data.sentiment[`${label}_comments_count`]}</strong></p>)}</div>:<p className="text-slate-400">No analyzed comments yet. There is not enough data to describe audience sentiment.</p>}</section></>}
 </div>;
}
