import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Layers, PenLine, CalendarDays, ShieldCheck, BarChart3, MessageSquare, Sparkles, ArrowRight } from 'lucide-react';

export default function LandingPage({ onLaunchDashboard, onOpenAuth }) {
  const features=[{icon:PenLine,title:'Create once. Make it yours.',text:'Write a shared draft, analyze its sentiment, and prepare content for your connected channels.'},{icon:CalendarDays,title:'A schedule you control.',text:'Choose your publishing time, review the queue, and see confirmed results for each platform.'},{icon:BarChart3,title:'Understand what happened.',text:'Bring account metrics and audience signals into one workspace. No connections? No invented numbers.'},{icon:MessageSquare,title:'Thoughtful replies.',text:'Review incoming comments and AI-assisted suggestions before sending a response.'},{icon:Sparkles,title:'AI, with context.',text:'Caption and hashtag tools support your decisions. Experimental forecasts are clearly labeled.'},{icon:ShieldCheck,title:'Security comes first.',text:'Verified accounts, optional authenticator 2FA, encrypted social credentials, and revocable sessions.'}];
  return <div className="min-h-screen overflow-x-clip bg-[#07090E] text-slate-100"><header className="max-w-7xl mx-auto px-5 sm:px-8 h-20 flex items-center justify-between border-b border-white/10"><Link to="/" className="flex items-center gap-3 font-bold text-xl"><span className="bg-brand-600 p-2 rounded-lg"><Layers size={22}/></span>AISMM<span className="hidden sm:inline text-slate-500 font-normal text-sm">/ social studio</span></Link><nav className="flex items-center gap-5"><a href="#features" className="text-sm text-slate-300 hidden sm:block">The workspace</a><button className="text-sm font-semibold" onClick={onOpenAuth}>Sign in <ArrowUpRight className="inline" size={16}/></button></nav></header>
    <main id="main-content"><section className="max-w-7xl mx-auto px-5 sm:px-8 pt-16 sm:pt-24 pb-16 grid lg:grid-cols-2 gap-12 lg:gap-16 items-center"><div><div className="inline-flex items-center gap-2 text-xs text-cyan-300 uppercase tracking-[.16em] mb-7"><span className="h-2 w-2 rounded-full bg-cyan-400"/>Your content. More intentional.</div><h1 className="text-5xl sm:text-6xl xl:text-7xl font-semibold tracking-tight leading-[1.06]">Less switching.<br/>More <span className="text-brand-400">creating.</span></h1><p className="mt-7 text-lg text-slate-400 leading-relaxed max-w-lg">Plan, publish, and learn from your social content in one focused workspace — with AI as your assistant, not your autopilot.</p><div className="flex flex-wrap gap-4 mt-8"><button className="btn px-6 py-3" onClick={onLaunchDashboard}>Create your workspace <ArrowRight size={18}/></button><a href="#features" className="btn-secondary px-6 py-3">Take a closer look</a></div><p className="mt-5 text-xs text-slate-500">Start with a clean workspace. Connect only the accounts you choose.</p></div>
    <div className="relative"><div className="absolute -inset-8 bg-brand-600/10 blur-3xl pointer-events-none"/><div className="relative border border-slate-700 rounded-2xl bg-[#0D121F] overflow-hidden shadow-2xl"><div className="p-4 border-b border-slate-800 flex justify-between text-xs"><span className="font-semibold text-slate-200 flex items-center gap-2"><Layers size={16} className="text-brand-400"/>AISMM / Composer</span><span className="text-slate-500">Product preview</span></div><div className="p-5 sm:p-7 space-y-6"><div className="flex justify-between items-center"><h2 className="font-semibold">Make your next post count.</h2><PenLine className="text-slate-500" size={18}/></div><div className="rounded-xl border border-slate-700 p-5 bg-obsidian-bg"><p className="text-slate-500 text-sm mb-8">A new idea starts here…</p><div className="h-2 bg-slate-800 rounded w-5/6 mb-3"/><div className="h-2 bg-slate-800 rounded w-3/5 mb-8"/><div className="text-xs text-brand-300 flex items-center gap-2"><Sparkles size={14}/>AI suggestions, on your terms</div></div><div className="grid grid-cols-2 gap-3"><div className="border border-slate-800 rounded-xl p-4"><CalendarDays size={20} className="text-cyan-300 mb-3"/><p className="text-sm font-semibold">Your timing</p><p className="text-xs text-slate-500 mt-1">Review before scheduling</p></div><div className="border border-slate-800 rounded-xl p-4"><ShieldCheck size={20} className="text-brand-300 mb-3"/><p className="text-sm font-semibold">Your accounts</p><p className="text-xs text-slate-500 mt-1">Explicit permission only</p></div></div><div className="flex justify-between text-xs text-slate-500 pt-2 border-t border-slate-800"><span>Write → Review → Publish</span><span>No sample analytics</span></div></div></div></div></section>
    <section id="features" className="max-w-7xl mx-auto px-5 sm:px-8 py-16 border-t border-white/10"><p className="text-xs tracking-widest uppercase text-cyan-300 mb-4">One connected workflow</p><h2 className="text-3xl sm:text-4xl font-semibold tracking-tight max-w-2xl">Everything has a place.<br/><span className="text-slate-500">Your attention stays on the work.</span></h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-10 gap-y-12 mt-12">{features.map(({icon:Icon,title,text})=><article key={title}><Icon size={24} className="text-brand-400 mb-5"/><h3 className="text-lg font-semibold mb-3">{title}</h3><p className="text-sm text-slate-400 leading-relaxed">{text}</p></article>)}</div></section>
    <section className="max-w-7xl mx-auto px-5 sm:px-8 pb-16"><div className="panel sm:p-10 flex flex-wrap items-center justify-between gap-6"><div><h2 className="text-2xl font-semibold">Build a calmer content workflow.</h2><p className="text-slate-400 mt-2 text-sm">Your first step is a blank workspace, not a wall of dashboards.</p></div><button className="btn px-6" onClick={onLaunchDashboard}>Get started <ArrowRight size={18}/></button></div><p className="text-xs text-slate-500 mt-5">Platform availability depends on operator configuration, provider approvals, and account permissions. Meta connections are not available yet. Experimental ML is not a guarantee of growth.</p></section></main>
    <footer className="border-t border-white/10"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-8 flex flex-wrap gap-6 justify-between text-sm text-slate-400"><span>AISMM · A more intentional social workspace.</span><div className="flex gap-6"><Link to="/terms">Terms</Link><Link to="/privacy">Privacy</Link><button onClick={onOpenAuth}>Sign in</button></div></div></footer>
  </div>;
}
