import React,{useState,useEffect} from 'react';
import {ArrowRight,Plus,Share2,RefreshCw} from 'lucide-react';
import {api} from '../api/client';
export default function OverviewTab({onNavigateTab}){
 const [data,setData]=useState(null),[posts,setPosts]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const [summary,recent]=await Promise.all([api.getOverview(),api.getPosts(1,5)]);setData(summary);setPosts(recent.posts||[]);}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 return <div className="space-y-6"><header className="flex flex-wrap gap-4 items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-cyan-300 mb-2">Your social workspace</p><h1 className="text-3xl font-semibold">A clearer view of your work.</h1><p className="text-slate-400 mt-2">Account activity and content, without the noise.</p></div><button className="btn" onClick={()=>onNavigateTab('composer')}><Plus size={18}/>Create a post</button></header>
 {error&&<div className="error" role="alert">{error}<button className="block underline mt-2" onClick={load}>Retry</button></div>}
 {loading&&<p role="status" className="text-slate-400">Loading workspace…</p>}
 {data&&<>{data.total_connected_platforms===0&&<section className="panel border-brand-500/40 flex flex-wrap justify-between items-center gap-6"><div><Share2 className="text-brand-400 mb-3"/><h2 className="text-xl font-semibold">Welcome to your new workspace.</h2><p className="text-slate-400 text-sm mt-2">No connected accounts or audience data yet. Connect your first platform to get started.</p></div><button className="btn-secondary" onClick={()=>onNavigateTab('platforms')}>Connect a platform<ArrowRight size={16}/></button></section>}
 <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[['Connected platforms',data.total_connected_platforms],['Published posts',data.total_posts_published],['Audience reach',data.total_reach],['Engagements',data.total_engagements]].map(([label,value])=><div key={label} className="panel"><p className="text-sm text-slate-400">{label}</p><p className="text-3xl font-semibold mt-4">{value?.toLocaleString()??'—'}</p><p className="text-xs text-slate-500 mt-3">Last {data.time_period_days} days</p></div>)}</div>
 <section className="panel"><div className="flex justify-between items-center mb-5"><h2 className="text-lg font-semibold">Recent content</h2><button className="text-sm text-brand-300" onClick={load} aria-label="Refresh overview"><RefreshCw size={18}/></button></div>{posts.length?posts.map(post=><div key={post.id} className="flex flex-wrap justify-between gap-3 py-4 border-t border-slate-800 text-sm"><span className="capitalize">{post.platform}</span><span>{post.status}</span><span className="text-slate-400">{post.scheduled_at?new Date(post.scheduled_at+'Z').toLocaleString():'Not scheduled'}</span>{post.permalink&&<a href={post.permalink} rel="noreferrer" target="_blank" className="text-brand-300 underline">View post</a>}</div>):<div className="text-center py-12"><p className="text-slate-300">Your story starts with the first draft.</p><p className="text-slate-500 text-sm mt-2">No posts have been created for this account.</p><button className="btn-secondary mt-5" onClick={()=>onNavigateTab('composer')}>Open composer</button></div>}</section></>}
 </div>;
}
