import React, { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { QRCodeSVG } from 'qrcode.react';
import { api, clearAuthSession } from '../api/client';

export default function SettingsTab({ onUser }) {
  const [user,setUser] = useState(null); const [name,setName] = useState('');
  const [error,setError] = useState(''); const [message,setMessage] = useState(''); const [busy,setBusy] = useState(false);
  const [setup,setSetup] = useState(null); const [code,setCode] = useState('');
  const [currentPassword,setCurrentPassword] = useState(''); const [password,setPassword] = useState('');
  const navigate = useNavigate(); const location = useLocation();
  const section = location.pathname.split('/')[3] || 'general';
  const load=()=>api.getMe().then(me=>{setUser(me);setName(me.full_name||'');}).catch(err=>setError(err.message));
  useEffect(()=>{load();},[]);
  async function action(fn) { setBusy(true);setError('');setMessage('');try{await fn();}catch(err){setError(err.message);}finally{setBusy(false);} }
  return <div className="space-y-6"><header><p className="text-cyan-300 text-xs tracking-widest uppercase mb-2">Your workspace</p><h1 className="text-2xl font-bold">Settings</h1><p className="text-slate-400 mt-2">Manage your profile and protect your account.</p></header>
    <nav className="flex flex-wrap gap-2" aria-label="Settings sections">{['general','security','notifications','apikeys'].map(id=><button key={id} className={section===id?'btn':'btn-secondary'} aria-current={section===id?'page':undefined} onClick={()=>navigate(`/app/settings/${id}`)}>{ {general:'Profile',security:'Security & 2FA',notifications:'Notifications',apikeys:'API keys'}[id]}</button>)}</nav>
    {error&&<div role="alert" className="error">{error}</div>}{message&&<div role="status" className="notice">{message}</div>}
    {!user&&!error&&<p role="status">Loading account settings…</p>}
    {user&&section==='general'&&<form className="panel max-w-2xl space-y-5" onSubmit={e=>{e.preventDefault();action(async()=>{const me=await api.updateProfile(name);setUser(me);onUser?.(me);setMessage('Profile saved.');});}}><h2 className="text-lg font-semibold">Your profile</h2><label className="block text-sm">Full name<input className="field mt-2" autoComplete="name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><div><p className="text-sm text-slate-400">Email address</p><p className="mt-1 break-all">{user.email}</p><p className="text-sm mt-1 text-cyan-300">{user.is_verified?'Email verified':'Email verification pending'}</p></div><button className="btn" disabled={busy}>Save profile</button></form>}
    {user&&section==='security'&&<div className="grid xl:grid-cols-2 gap-6"><section className="panel space-y-5"><h2 className="text-lg font-semibold">Two-factor authentication</h2><p className="text-slate-400 text-sm">Add an authenticator app as a second sign-in step. Keep its backup safely; email password recovery does not remove 2FA.</p><p className="notice">{user.two_factor_enabled?'Enabled — an authenticator code is required at sign-in.':'Not enabled — protect your account with a second factor.'}</p>
      {!setup&&!user.two_factor_enabled&&<button className="btn" disabled={busy} onClick={()=>action(async()=>setSetup(await api.setup2fa()))}>Set up authenticator</button>}
      {setup&&<div className="space-y-4"><div className="bg-white rounded-lg p-4 w-fit"><QRCodeSVG value={setup.otpauth_url} size={180} title="Scan with your authenticator app"/></div><p className="text-sm text-slate-400">Scan this QR code or enter the setup key manually. Never share this key.</p><code className="block break-all text-sm">{setup.secret}</code></div>}
      {(setup||user.two_factor_enabled)&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();action(async()=>{if(user.two_factor_enabled)await api.disable2fa(code);else await api.enable2fa(code);setCode('');setSetup(null);await load();setMessage('Two-factor settings updated.');});}}><label className="block text-sm">Authenticator code<input className="field mt-2" autoComplete="one-time-code" inputMode="numeric" required pattern="[0-9]{6}" value={code} onChange={e=>setCode(e.target.value)}/></label><button className="btn" disabled={busy}>{user.two_factor_enabled?'Disable 2FA':'Verify and enable 2FA'}</button></form>}
    </section><form className="panel space-y-5" onSubmit={e=>{e.preventDefault();action(async()=>{await api.changePassword({current_password:currentPassword,password,two_factor_code:code||undefined});clearAuthSession();window.dispatchEvent(new Event('aismm:session-expired'));});}}><h2 className="text-lg font-semibold">Change password</h2><p className="text-sm text-slate-400">Changing your password signs you out on all devices.</p><label className="block text-sm">Current password<input className="field mt-2" type="password" autoComplete="current-password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label className="block text-sm">New password<input className="field mt-2" type="password" autoComplete="new-password" minLength={8} maxLength={72} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{user.two_factor_enabled&&<label className="block text-sm">Authenticator code<input className="field mt-2" autoComplete="one-time-code" inputMode="numeric" required pattern="[0-9]{6}" value={code} onChange={e=>setCode(e.target.value)}/></label>}<button className="btn" disabled={busy}>Change password & sign out</button></form></div>}
    {['notifications','apikeys'].includes(section)&&<div className="panel max-w-2xl"><h2 className="text-lg font-semibold mb-3">Not available yet</h2><p className="text-slate-400">{section==='apikeys'?'Workspace API key issuance is not implemented. No sample keys are shown or issued. Use the browser sign-in flow.':'Custom notification preferences are not implemented. Account verification and password recovery emails use the configured transactional provider.'}</p></div>}
  </div>;
}
