// Browser acceptance against local build + real local API through CDP.
const fs=require('fs');const path=require('path');const crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const {chromium}=require(require.resolve('@playwright/test',{paths:[path.join(root,'frontend')]}));
const artifacts=path.join(root,'artifacts');fs.mkdirSync(artifacts,{recursive:true});
if(!process.env.AGENT_BROWSER_CDP)throw Error('Set AGENT_BROWSER_CDP to an existing Chromium debug connection. Test accounts are created locally; never use production.');
(async()=>{const browser=await chromium.connectOverCDP(process.env.AGENT_BROWSER_CDP);const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const base='http://aismm.local';const results=[];const errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error' && !msg.text().includes('Failed to load resource'))errors.push(msg.text().slice(0,400));});
await context.route('http://aismm.local/**',async route=>{const req=route.request();const u=new URL(req.url());try{if(u.pathname.startsWith('/api/')){const headers={...req.headers()};delete headers.host;const r=await fetch('http://127.0.0.1:8000'+u.pathname+u.search,{method:req.method(),headers,body:['GET','HEAD'].includes(req.method())?undefined:req.postDataBuffer()});const body=Buffer.from(await r.arrayBuffer());if(r.status>=400)results.push({api:u.pathname,status:r.status});await route.fulfill({status:r.status,headers:{'content-type':r.headers.get('content-type')||'application/json'},body});}else{let file=path.join(path.join(root,'frontend/dist'),u.pathname);if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(root,'frontend/dist/index.html');const ext=path.extname(file);await route.fulfill({status:200,contentType:({'.js':'application/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml'})[ext]||'application/octet-stream',body:fs.readFileSync(file)});}}catch(e){errors.push('proxy '+e.message);await route.abort();}});
try{
await page.goto(base);await page.getByRole('heading',{name:/Less switching/}).waitFor();await page.screenshot({path:path.join(artifacts,'landing-desktop.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,'landing-mobile.png'),fullPage:true});results.push({route:'landing',overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});
await page.goto(base+'/register');await page.getByLabel('Full name',{exact:true}).fill('QA Workspace');await page.getByLabel('Email',{exact:true}).fill(`qa-${Date.now()}@example.com`);await page.getByLabel('Password',{exact:true}).fill(crypto.randomBytes(18).toString('hex'));await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create account',exact:true}).click();await page.getByRole('button',{name:'Verify email',exact:true}).waitFor({timeout:30000});await page.getByRole('button',{name:'Verify email',exact:true}).click();await page.waitForURL('**/app/overview');await page.getByText('Welcome to your new workspace.').waitFor({timeout:30000});await page.screenshot({path:path.join(artifacts,'overview-mobile.png'),fullPage:true});results.push({test:'registration and email verification',passed:true});
await page.setViewportSize({width:1440,height:1000});
const tabs=['overview','analytics','composer','scheduling','ai-engine','inbox','growth','platforms','strategy','reports','models','settings','security'];
for(const tab of tabs){await page.goto(base+'/app/'+tab);await page.waitForLoadState('networkidle');await page.screenshot({path:path.join(artifacts,`${tab}-desktop.png`),fullPage:true});const text=await page.locator('main').innerText();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,`${tab}-mobile.png`),fullPage:true});const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await page.setViewportSize({width:1440,height:1000});results.push({route:tab,mobileOverflow,overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),error:/Unable to|Offline|Something went wrong/i.test(text),text:text.slice(0,220)});}
await page.goto(base+'/app/composer');await page.getByPlaceholder('What would you like to share?').fill('Persist this unsent QA draft');await page.getByRole('button',{name:'Analytics',exact:true}).click();await page.getByRole('button',{name:'Composer',exact:true}).click();if(await page.getByPlaceholder('What would you like to share?').inputValue()!=='Persist this unsent QA draft')throw Error('Draft lost navigating');await page.reload();await page.getByPlaceholder('What would you like to share?').waitFor();if(await page.getByPlaceholder('What would you like to share?').inputValue()!=='Persist this unsent QA draft')throw Error('Draft lost reloading');results.push({test:'draft continuity',passed:true});
await page.goto(base+'/app/settings/security');await page.getByRole('button',{name:'Set up authenticator'}).click();await page.getByText('Scan this QR code or enter the setup key manually. Never share this key.').waitFor();await page.screenshot({path:path.join(artifacts,'settings-security.png'),fullPage:true,mask:[page.locator('code'),page.locator('svg').filter({has:page.locator('path')}).last()]});
await page.getByTitle('Sign Out').click();await page.waitForURL(/\/(login)?$/);await page.goto(base+'/app/overview');await page.waitForURL('**/login');results.push({test:'logout and protected direct route',passed:true});
}catch(e){errors.push(e.message);await page.screenshot({path:path.join(artifacts,'browser-failure.png'),fullPage:true});}
fs.writeFileSync(path.join(artifacts,'browser-results.json'),JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));await page.close();await context.close();process.exit(errors.length?1:0);
})().catch(e=>{console.error(e.message);process.exit(1)});
